version: "3.4"
services:

    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./html:/var/www/html/
        links:
            - db
        depends_on:
            - db

    db:
        image: mariadb:10.3
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: toor
        volumes:
            - persistent:/var/lib/mysql

volumes:
    persistent: